"""Export a Register's bit-field layout as C source.

Two styles are supported:

- "defines" (default): portable `#define` position/mask macros plus
  SET/GET helper macros. This is the recommended style — plain bitwise ops
  on an integer behave identically on every compiler and target.
- "struct": a C bit-field struct. Reads nicer, but C leaves the bit
  allocation order of struct bit-fields implementation-defined — see the
  caveat comment emitted in the generated code before you rely on it
  matching hardware layout exactly.
"""

from __future__ import annotations

import re

from .core import Register

_C_TYPE_BY_MAX_BITS = [(8, "uint8_t"), (16, "uint16_t"), (32, "uint32_t"), (64, "uint64_t")]


def _sanitize_identifier(name: str) -> str:
    ident = re.sub(r"[^0-9a-zA-Z_]", "_", name).strip("_")
    if ident and ident[0].isdigit():
        ident = f"_{ident}"
    return ident or "REG"


def _c_type_for(size_bits: int) -> str:
    for max_bits, ctype in _C_TYPE_BY_MAX_BITS:
        if size_bits <= max_bits:
            return ctype
    raise ValueError(f"No C integer type large enough for a {size_bits}-bit register")


def export_c(reg: Register, style: str = "defines") -> str:
    """Returns C source for `reg`.

    Args:
        reg: The register to export.
        style: "defines" (default, portable) or "struct" (readable, but see
            the portability caveat in the module docstring / generated
            comment).
    """
    if style == "defines":
        return _export_defines(reg)
    if style == "struct":
        return _export_struct(reg)
    raise ValueError(f"Unknown style {style!r} (expected 'defines' or 'struct')")


def _export_defines(reg: Register) -> str:
    prefix = _sanitize_identifier(reg.name)
    ctype = _c_type_for(reg.size_bits)
    lines = [
        f"/* Generated by bitlab.registers.codegen.export_c -- {reg.name} "
        f"({reg.size_bits}-bit register) */",
        "#include <stdint.h>",
        "",
    ]

    for field in reg.layout():
        fname = _sanitize_identifier(field.name)
        comment = f"  /* {field.description} */" if field.description else ""
        lines.append(f"#define {prefix}_{fname}_POS   {field.start}U{comment}")
        lines.append(f"#define {prefix}_{fname}_MASK  (0x{field.max_value:X}U << {prefix}_{fname}_POS)")
        lines.append("")

    for field in reg.layout():
        fname = _sanitize_identifier(field.name)
        lines.append(
            f"#define {prefix}_SET_{fname}(reg, val) \\\n"
            f"    ((reg) = (({ctype})(reg) & ~{prefix}_{fname}_MASK) | "
            f"((({ctype})(val) << {prefix}_{fname}_POS) & {prefix}_{fname}_MASK))"
        )
        lines.append(
            f"#define {prefix}_GET_{fname}(reg) \\\n"
            f"    ((({ctype})(reg) & {prefix}_{fname}_MASK) >> {prefix}_{fname}_POS)"
        )
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _export_struct(reg: Register) -> str:
    prefix = _sanitize_identifier(reg.name)
    ctype = _c_type_for(reg.size_bits)

    lines = [
        f"/* Generated by bitlab.registers.codegen.export_c -- {reg.name} "
        f"({reg.size_bits}-bit register) */",
        "/*",
        " * NOTE: C leaves the bit allocation order of struct bit-fields",
        " * implementation-defined (C99 6.7.2.1p10). Most common compilers for",
        " * little-endian embedded targets (e.g. GCC/Clang on ARM Cortex-M) pack",
        " * the first-declared field at the LEAST significant bit -- matching the",
        " * layout below and bitlab's Python pack()/unpack() -- but this is not",
        " * guaranteed by the C standard. Verify against your compiler's",
        " * documentation, or prefer the portable #define/mask style",
        " * (export_c(reg, style='defines')) if exact bit placement matters.",
        " */",
        "#include <stdint.h>",
        "",
        "typedef struct {",
    ]

    # Ascending bit order (LSB first), matching Python's bit 0 = LSB convention.
    covered = {}
    for field in reg.fields.values():
        covered[field.start] = field

    reserved_index = 0
    bit = 0
    while bit < reg.size_bits:
        if bit in covered:
            field = covered[bit]
            fname = _sanitize_identifier(field.name)
            comment = f"  /* {field.description} */" if field.description else ""
            lines.append(f"    {ctype} {fname} : {field.width};{comment}")
            bit += field.width
        else:
            lines.append(f"    {ctype} _RESERVED_{reserved_index} : 1;")
            reserved_index += 1
            bit += 1

    lines.append(f"}} {prefix}_t;")
    return "\n".join(lines) + "\n"
