"""Export endianness-swap functions and Q-format conversion macros as C
source.

IEEE 754 deconstruction and Gray code aren't included here: C already
exposes native bit-exact float access via type punning (a union or
`memcpy`), and Gray code is a one-line `n ^ (n >> 1)` that doesn't benefit
from generated boilerplate. Byte-swapping and Q-format conversion, on the
other hand, are things embedded projects reimplement (and sometimes get
subtly wrong) constantly, so those get real code generation.
"""

from __future__ import annotations

from .fixed_point import parse_q_format

_UINT_TYPE_BY_BYTES = {1: "uint8_t", 2: "uint16_t", 4: "uint32_t", 8: "uint64_t"}


def export_c_endian_swap(width_bytes: int, function_name: str = None) -> str:
    """Returns a C99 `static inline` function that reverses the byte order
    of a `width_bytes`-wide unsigned integer.

    Args:
        width_bytes: 2, 4, or 8.
        function_name: Optional explicit name. Defaults to
            `swap_endianness_<bits>`.
    """
    if width_bytes not in (2, 4, 8):
        raise ValueError(f"export_c_endian_swap only supports width_bytes 2, 4, or 8 (got {width_bytes})")

    ctype = _UINT_TYPE_BY_BYTES[width_bytes]
    bits = width_bytes * 8
    fn_name = function_name or f"swap_endianness_{bits}"

    terms = []
    for i in range(width_bytes):
        src_shift = i * 8
        dst_shift = (width_bytes - 1 - i) * 8
        mask = f"0x{0xFF << src_shift:0{width_bytes * 2}X}U"
        if src_shift == dst_shift:
            terms.append(f"(value & {mask})")
        elif dst_shift > src_shift:
            terms.append(f"((value & {mask}) << {dst_shift - src_shift})")
        else:
            terms.append(f"((value & {mask}) >> {src_shift - dst_shift})")

    body = " |\n           ".join(terms)

    return (
        f"/* Generated by bitlab.arch.codegen.export_c_endian_swap ({bits}-bit) */\n"
        f"#include <stdint.h>\n\n"
        f"static inline {ctype} {fn_name}({ctype} value)\n"
        f"{{\n"
        f"    return {body};\n"
        f"}}\n"
    )


def export_c_fixed_point(q_format: str, prefix: str = None) -> str:
    """Returns C macros for converting to/from a Q-format fixed-point value.

    Args:
        q_format: e.g. "Q8.8" or "Q1.15".
        prefix: Optional macro name prefix. Defaults to a sanitized version
            of `q_format` (e.g. "Q1.15" -> "Q1_15").
    """
    integer_bits, fractional_bits = parse_q_format(q_format)
    width = integer_bits + fractional_bits
    scale = 1 << fractional_bits

    int_type = None
    for max_bits, ctype in ((8, "int8_t"), (16, "int16_t"), (32, "int32_t"), (64, "int64_t")):
        if width <= max_bits:
            int_type = ctype
            break
    if int_type is None:
        raise ValueError(f"{q_format} needs {width} bits, no C integer type is that wide")

    name = prefix or q_format.replace(".", "_")

    return (
        f"/* Generated by bitlab.arch.codegen.export_c_fixed_point -- {q_format} "
        f"({integer_bits} integer bit(s) incl. sign + {fractional_bits} fractional bits) */\n"
        f"#include <stdint.h>\n\n"
        f"#define {name}_SCALE ({scale})\n"
        f"#define {name}_FROM_FLOAT(f) (({int_type})((f) * {name}_SCALE))\n"
        f"#define {name}_TO_FLOAT(raw) ((float)(raw) / {name}_SCALE)\n"
    )
