"""Export COBS encode/decode as standalone C source.

Unlike the CRC/register exporters, there's no lookup table or per-config
parameterization here — COBS has no "variant" to configure, so this simply
emits a fixed, well-tested reference implementation in C99. It's still
worth generating (rather than just telling people to look it up) because
getting the block-boundary bookkeeping exactly right by hand is a common
source of subtle firmware bugs; this version is validated by actually
compiling it and property-testing it against the Python implementation.
"""

from __future__ import annotations

import re


def _sanitize_identifier(name: str) -> str:
    ident = re.sub(r"[^0-9a-zA-Z_]", "_", name).strip("_")
    if ident and ident[0].isdigit():
        ident = f"_{ident}"
    return ident or "cobs"


def export_c(encode_fn_name: str = "cobs_encode", decode_fn_name: str = "cobs_decode") -> str:
    """Returns standalone C99 source implementing COBS encode and decode.

    Args:
        encode_fn_name: Name for the generated encode function.
        decode_fn_name: Name for the generated decode function.
    """
    enc = _sanitize_identifier(encode_fn_name)
    dec = _sanitize_identifier(decode_fn_name)

    return f"""/* Generated by bitlab.comms.codegen.export_c -- COBS
 * (Consistent Overhead Byte Stuffing). Reference: Cheshire & Baker, IEEE/ACM
 * ToN 1999. Validated by compiling with gcc and property-testing against
 * bitlab's Python implementation on randomized inputs.
 */
#include <stdint.h>
#include <stddef.h>

/* Encodes src[0..len) into dst using COBS. dst must have room for at least
 * len + (len / 254) + 1 bytes. Returns the number of bytes written to dst.
 * The output never contains a zero byte -- a single 0x00 can safely be
 * appended by the caller as a frame delimiter. */
size_t {enc}(const uint8_t *src, size_t len, uint8_t *dst)
{{
    size_t write_index = 1;
    size_t code_index = 0;
    uint8_t code = 1;

    for (size_t i = 0; i < len; i++) {{
        if (src[i] == 0) {{
            dst[code_index] = code;
            code_index = write_index++;
            code = 1;
        }} else {{
            dst[write_index++] = src[i];
            code++;
            if (code == 0xFF) {{
                dst[code_index] = code;
                code_index = write_index++;
                code = 1;
            }}
        }}
    }}
    dst[code_index] = code;
    return write_index;
}}

/* Decodes src[0..len) (a COBS-encoded block, WITHOUT the trailing 0x00
 * delimiter) into dst. dst must have room for at least len bytes. Returns
 * the number of bytes written to dst, or (size_t)-1 if src is malformed
 * (embedded zero byte, or truncated final block). */
size_t {dec}(const uint8_t *src, size_t len, uint8_t *dst)
{{
    size_t read_index = 0;
    size_t write_index = 0;

    while (read_index < len) {{
        uint8_t code = src[read_index];
        if (code == 0) {{
            return (size_t)-1;
        }}
        read_index++;

        size_t remaining = (size_t)(code - 1);
        if (read_index + remaining > len) {{
            return (size_t)-1;
        }}
        for (size_t i = 0; i < remaining; i++) {{
            if (src[read_index] == 0) {{
                return (size_t)-1;
            }}
            dst[write_index++] = src[read_index++];
        }}

        if (code < 0xFF && read_index < len) {{
            dst[write_index++] = 0;
        }}
    }}
    return write_index;
}}
"""
