"""Export a CRC configuration as standalone, table-driven C source.

This is what turns bitlab from "a Python learning tool" into something an
embedded developer actually keeps: design/verify a CRC in Python, then drop
the generated C straight into a firmware project. The lookup table embedded
in the generated code is built by the exact same `engine.build_table` used
by bitlab's own fast Python path, so the C output and the Python output are
guaranteed to agree.
"""

from __future__ import annotations

import re

from ..bitutils import reflect
from .engine import build_table
from .presets import CRCConfig

_C_TYPE_BY_WIDTH = {8: "uint8_t", 16: "uint16_t", 32: "uint32_t"}


def _sanitize_identifier(name: str) -> str:
    ident = re.sub(r"[^0-9a-zA-Z_]", "_", name.lower())
    ident = re.sub(r"_+", "_", ident).strip("_")
    if ident and ident[0].isdigit():
        ident = f"_{ident}"
    return ident or "crc"


def export_c(config: CRCConfig, function_name: str = None) -> str:
    """Returns standalone C source (C99) implementing `config` as a
    table-driven CRC function with an embedded 256-entry lookup table.

    Args:
        config: The CRC configuration to export.
        function_name: Optional explicit C function name. Defaults to a
            sanitized version of `config.name` (e.g. "CRC-32/ISO-HDLC" ->
            "crc_32_iso_hdlc").
    """
    if config.width not in _C_TYPE_BY_WIDTH:
        raise ValueError(
            f"export_c only supports width 8, 16, or 32 (got {config.width})"
        )

    ctype = _C_TYPE_BY_WIDTH[config.width]
    fn_name = function_name or _sanitize_identifier(config.name)
    hexw = config.width // 4
    table = build_table(config)

    rows = []
    for i in range(0, 256, 8):
        row = ", ".join(f"0x{v:0{hexw}X}" for v in table[i : i + 8])
        rows.append("    " + row + ",")
    table_str = "\n".join(rows)

    if config.refin:
        init_val = reflect(config.init, config.width)
        body = (
            f"    {ctype} crc = 0x{init_val:0{hexw}X}U;\n"
            f"    for (size_t i = 0; i < len; i++) {{\n"
            f"        uint8_t idx = (uint8_t)(crc ^ data[i]);\n"
            f"        crc = (crc >> 8) ^ {fn_name}_table[idx];\n"
            f"    }}\n"
            f"    return (crc ^ 0x{config.xorout:0{hexw}X}U);"
        )
    else:
        shift = config.width - 8
        body = (
            f"    {ctype} crc = 0x{config.init:0{hexw}X}U;\n"
            f"    for (size_t i = 0; i < len; i++) {{\n"
            f"        uint8_t idx = (uint8_t)((crc >> {shift}) ^ data[i]);\n"
            f"        crc = (crc << 8) ^ {fn_name}_table[idx];\n"
            f"    }}\n"
            f"    return (crc ^ 0x{config.xorout:0{hexw}X}U);"
        )

    return (
        f"/* Generated by bitlab.crc.codegen.export_c -- {config.name}\n"
        f" * width={config.width} poly=0x{config.poly:0{hexw}X} init=0x{config.init:0{hexw}X}\n"
        f" * refin={config.refin} refout={config.refout} xorout=0x{config.xorout:0{hexw}X}\n"
        f" */\n"
        f"#include <stdint.h>\n"
        f"#include <stddef.h>\n\n"
        f"static const {ctype} {fn_name}_table[256] = {{\n"
        f"{table_str}\n"
        f"}};\n\n"
        f"{ctype} {fn_name}(const uint8_t *data, size_t len)\n"
        f"{{\n"
        f"{body}\n"
        f"}}\n"
    )
